### PR TITLE
Add a report as per issue #5

### PR DESCRIPTION
**Pull request by Firesphere**

### CODE REVIEW

**Comment by silbinarywolf** [comment]
Please use PHP 5.3 array() syntax as that's the lowest supported version.

**Comment by Firesphere** [comment]
Hah, sure, I'll update :)

**Comment by silbinarywolf** [comment]
Sweet, once this goes in, I'll tag as 1.1.0. 
Oh! Wrap this in class_exists('SS_Report') as well, as 3.3+, "reports" is an optional module right?

**Comment by Firesphere** [comment]
Yep, it's indeed optional, will do :)

**Comment by silbinarywolf** [comment]
When I select "No action taken" in the DropdownField and hit filter, it reverts the selection to the default value. Most likely due to ClamAVScan::ACTION_NONE being 0. Any workaround for this or similar?

**Comment by Firesphere** [comment]
Ow, didn't realize that, yes, I think I can find a solution for that :)

Also, I think I broke everything in the report completely :/

**Comment by Firesphere** [comment]
Fixed the report issue and had to add a config. Accidentally also committed some stuff generated by dev/build. Just a sec

**Comment by Firesphere** [comment]
Everything should be working now :) Rebased on Master

**Comment by silbinarywolf** [comment]
Remove the config.yml file you added. It's empty and doesn't configure anything.

**Comment by Firesphere** [comment]
The config.yml is not empty. It's instructing the manifest-builder to include the module _after_ CMS and Framework. Without it, the Reports-module isn't loaded yet (as CMS looks for it), and thus the report isn't included because of the `class_exists` statement.

I'm unsure as to why the module is loaded before CMS, but otherwise it doesn't include the report.

**Comment by silbinarywolf** [comment]
When I delete it and test locally, the report shows up just fine.
What you're describing doesn't sound like how the manifest building works at all.

**Comment by Firesphere** [comment]
Hmmm, you're right, weird.

I guess I had something going on my local machine. It didn't show up for me when I added the class_exists. Then when I added the config file, it showed up again, so I figured it had something with the manifest to do. But now it indeed works fine without the config yml.

**Comment by silbinarywolf** [comment]
Thanks! Nice work. Merged in :)

**Comment by Firesphere** [comment]
I still want to find out what weird issue I had with the report not working until I added the config, and then the report working after removing everything though. :D

**Pull request merged**
